# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'klisfer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  #Pods for klisfer
    pod ‘GoogleSignIn’
    pod ‘Firebase’
    pod ‘Firebase/Core’
    pod ‘Firebase/Auth’
    pod ‘Firebase/Firestore’
    pod ‘Firebase/Storage’
    pod ‘Firebase/Database’
    pod 'PMSuperButton'
    pod 'JASON', '~> 3.0'
  
 use_frameworks! 
   pod 'UICheckbox.Swift'
   pod 'FontAwesome.swift'
   pod 'FontAwesomeKit'
   pod 'M13Checkbox'
   pod 'MaterialTextField', '~> 0.2'
   pod 'SkyFloatingLabelTextField', '~> 3.0'
   pod 'FontAwesomeKit', '~> 2.2.0'
   pod 'ActionSheetPicker-3.0', '~> 2.3.0'
   pod 'Kingfisher', '~> 4.0'
   pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
    
   pod 'Alamofire', '~> 4.5'
   pod 'JSSAlertView', '~> 3.0.4'
   pod 'BEMCheckBox'
   pod 'DynamicColor', '~> 4.0.1'



   use_frameworks!
   pod 'DatePickerDialog'


  source 'https://github.com/CocoaPods/Specs.git' 
  platform :ios, '8.0'
  use_frameworks!
  pod 'Material', '~> 2.0'
  
   

 #Pods for Facebook
    pod ‘Bolts’
    pod ‘FBSDKCoreKit’
    pod ‘FBSDKShareKit’
    pod ‘FBSDKLoginKit’
   

  target 'klisferTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'klisferUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
